### ISSUE TITLE
Ask Eric about opening up drupal-boilerplate

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/github-pm#2]
https://github.com/Lullabot/drupal-boilerplate

I like using parts of this for beginning a project and would like to be able to mention and link to it within the article.

cc: @ericduran

**Comment by ericduran** [comment]
Yea, I think I wanted to finish it up, but I guess if its public I'll wrap it up quicker. Feel free to open source it.

**Comment by sirkitree** [comment]
It's been made public and linked to in the article. Thanks @ericduran! I really do find this useful when setting up new projects :)

If you'd like to say more about it, feel free to send a pull request to this article. :)

**Comment by ericduran** [comment]
@sirkitree cool, I went ahead a created a gh-pages branch on the Drupal-boilerplate project. So it now has a website over at http://lullabot.github.com/drupal-boilerplate (still being published)

**Comment by sirkitree** [comment]
awesome! :)
